version: '3'
services:
  # 데이터베이스(MariaDB)
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mydb
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  # Zookeeper (Kafka를 위해 필요)
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_ANONYMOUS_LOGIN=yes

  # 스프링 부트(Gradle 빌드된 JAR) 컨테이너
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mariadb
      - kafka
    ports:
      - "8080:8080"
    # 환경변수 예시 (DB연결, Kafka연결 등)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
